### ISSUE TITLE
Any chance to add support for multiple by looking at address pads on the board?

### ISSUE THREAD

**Issue by ashishgururani** [pbugalski/wemos_motor_shield#4]
Looks like it is currently hardcoded https://github.com/pbugalski/wemos_motor_shield/blob/master/src/main.c#L72 to only 1 i2c address. I am trying to use two of these in my project.

If not, can you point me to how to compile and create a bin file?

https://forum.wemos.cc/topic/444/wemos-d1-mini-motor-shield-i2c-address-issue/2

**Comment by pbugalski** [comment]
Solved
